"""reconciliation-ready: entity/fact split, provenance, raw records, external ids

Revision ID: 00531f09d08f
Revises: 06582eecf0b2
Create Date: 2026-07-22 15:24:49.272035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00531f09d08f'
down_revision: Union[str, Sequence[str], None] = '06582eecf0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_records',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('http_status', sa.SmallInteger(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('storage_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_raw_records_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_records')),
    schema='raw_scrape'
    )
    op.create_index('idx_raw_records_content_hash', 'raw_records', ['content_hash'], unique=False, schema='raw_scrape')
    op.create_index(op.f('idx_raw_records_source_id'), 'raw_records', ['source_id'], unique=False, schema='raw_scrape')
    op.create_index('idx_raw_records_source_id_external_id', 'raw_records', ['source_id', 'external_id'], unique=False, schema='raw_scrape')
    op.create_table('external_ids',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('generation_id', sa.Integer(), nullable=True),
    sa.Column('model_year_id', sa.Integer(), nullable=True),
    sa.Column('configuration_id', sa.Integer(), nullable=True),
    sa.Column('engine_id', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(make_id, model_id, generation_id, model_year_id, configuration_id, engine_id, transmission_id) = 1', name=op.f('ck_external_ids_exactly_one_entity')),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], name=op.f('fk_external_ids_configuration_id_configurations')),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], name=op.f('fk_external_ids_engine_id_engines')),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], name=op.f('fk_external_ids_generation_id_generations')),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], name=op.f('fk_external_ids_make_id_makes')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_external_ids_model_id_models')),
    sa.ForeignKeyConstraint(['model_year_id'], ['model_years.id'], name=op.f('fk_external_ids_model_year_id_model_years')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_external_ids_source_id_sources')),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmissions.id'], name=op.f('fk_external_ids_transmission_id_transmissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_ids')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_external_ids_source_id_external_id')
    )
    op.create_index(op.f('idx_external_ids_configuration_id'), 'external_ids', ['configuration_id'], unique=False)
    op.create_index(op.f('idx_external_ids_engine_id'), 'external_ids', ['engine_id'], unique=False)
    op.create_index(op.f('idx_external_ids_generation_id'), 'external_ids', ['generation_id'], unique=False)
    op.create_index(op.f('idx_external_ids_make_id'), 'external_ids', ['make_id'], unique=False)
    op.create_index(op.f('idx_external_ids_model_id'), 'external_ids', ['model_id'], unique=False)
    op.create_index(op.f('idx_external_ids_model_year_id'), 'external_ids', ['model_year_id'], unique=False)
    op.create_index(op.f('idx_external_ids_source_id'), 'external_ids', ['source_id'], unique=False)
    op.create_index(op.f('idx_external_ids_transmission_id'), 'external_ids', ['transmission_id'], unique=False)
    op.create_table('field_provenance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('generation_id', sa.Integer(), nullable=True),
    sa.Column('model_year_id', sa.Integer(), nullable=True),
    sa.Column('configuration_id', sa.Integer(), nullable=True),
    sa.Column('engine_id', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('observed_value', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('raw_record_id', sa.BigInteger(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_field_provenance_confidence_range')),
    sa.CheckConstraint('num_nonnulls(make_id, model_id, generation_id, model_year_id, configuration_id, engine_id, transmission_id) = 1', name=op.f('ck_field_provenance_exactly_one_entity')),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], name=op.f('fk_field_provenance_configuration_id_configurations')),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], name=op.f('fk_field_provenance_engine_id_engines')),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], name=op.f('fk_field_provenance_generation_id_generations')),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], name=op.f('fk_field_provenance_make_id_makes')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_field_provenance_model_id_models')),
    sa.ForeignKeyConstraint(['model_year_id'], ['model_years.id'], name=op.f('fk_field_provenance_model_year_id_model_years')),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_scrape.raw_records.id'], name=op.f('fk_field_provenance_raw_record_id_raw_records')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_field_provenance_source_id_sources')),
    sa.ForeignKeyConstraint(['superseded_by'], ['field_provenance.id'], name=op.f('fk_field_provenance_superseded_by_field_provenance')),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmissions.id'], name=op.f('fk_field_provenance_transmission_id_transmissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_provenance'))
    )
    op.create_index('idx_field_provenance_configuration_id', 'field_provenance', ['configuration_id'], unique=False, postgresql_where=sa.text('configuration_id IS NOT NULL'))
    op.create_index('idx_field_provenance_engine_id', 'field_provenance', ['engine_id'], unique=False, postgresql_where=sa.text('engine_id IS NOT NULL'))
    op.create_index('idx_field_provenance_generation_id', 'field_provenance', ['generation_id'], unique=False, postgresql_where=sa.text('generation_id IS NOT NULL'))
    op.create_index('idx_field_provenance_make_id', 'field_provenance', ['make_id'], unique=False, postgresql_where=sa.text('make_id IS NOT NULL'))
    op.create_index('idx_field_provenance_model_id', 'field_provenance', ['model_id'], unique=False, postgresql_where=sa.text('model_id IS NOT NULL'))
    op.create_index('idx_field_provenance_model_year_id', 'field_provenance', ['model_year_id'], unique=False, postgresql_where=sa.text('model_year_id IS NOT NULL'))
    op.create_index(op.f('idx_field_provenance_raw_record_id'), 'field_provenance', ['raw_record_id'], unique=False)
    op.create_index(op.f('idx_field_provenance_source_id'), 'field_provenance', ['source_id'], unique=False)
    op.create_index('idx_field_provenance_source_id_field_name', 'field_provenance', ['source_id', 'field_name'], unique=False)
    op.create_index(op.f('idx_field_provenance_superseded_by'), 'field_provenance', ['superseded_by'], unique=False)
    op.create_index('idx_field_provenance_transmission_id', 'field_provenance', ['transmission_id'], unique=False, postgresql_where=sa.text('transmission_id IS NOT NULL'))
    op.add_column('configuration_attributes', sa.Column('raw_record_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('idx_configuration_attributes_raw_record_id'), 'configuration_attributes', ['raw_record_id'], unique=False)
    op.create_foreign_key(op.f('fk_configuration_attributes_raw_record_id_raw_records'), 'configuration_attributes', 'raw_records', ['raw_record_id'], ['id'], referent_schema='raw_scrape')
    op.add_column('configuration_engines', sa.Column('raw_record_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('idx_configuration_engines_raw_record_id'), 'configuration_engines', ['raw_record_id'], unique=False)
    op.create_foreign_key(op.f('fk_configuration_engines_raw_record_id_raw_records'), 'configuration_engines', 'raw_records', ['raw_record_id'], ['id'], referent_schema='raw_scrape')
    op.add_column('configuration_transmissions', sa.Column('raw_record_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('idx_configuration_transmissions_raw_record_id'), 'configuration_transmissions', ['raw_record_id'], unique=False)
    op.create_foreign_key(op.f('fk_configuration_transmissions_raw_record_id_raw_records'), 'configuration_transmissions', 'raw_records', ['raw_record_id'], ['id'], referent_schema='raw_scrape')
    op.drop_index(op.f('idx_configurations_source_id'), table_name='configurations')
    op.drop_index(op.f('idx_configurations_superseded_by'), table_name='configurations')
    op.drop_constraint(op.f('uq_configurations_wikidata_qid'), 'configurations', type_='unique')
    op.drop_constraint(op.f('fk_configurations_superseded_by_configurations'), 'configurations', type_='foreignkey')
    op.drop_constraint(op.f('fk_configurations_source_id_sources'), 'configurations', type_='foreignkey')
    op.drop_column('configurations', 'wikidata_qid')
    op.drop_column('configurations', 'source_id')
    op.drop_column('configurations', 'superseded_by')
    op.drop_column('configurations', 'scraped_at')
    op.drop_column('configurations', 'confidence_score')
    op.drop_index(op.f('idx_engines_source_id'), table_name='engines')
    op.drop_index(op.f('idx_engines_superseded_by'), table_name='engines')
    op.drop_constraint(op.f('uq_engines_wikidata_qid'), 'engines', type_='unique')
    op.drop_constraint(op.f('fk_engines_superseded_by_engines'), 'engines', type_='foreignkey')
    op.drop_constraint(op.f('fk_engines_source_id_sources'), 'engines', type_='foreignkey')
    op.drop_column('engines', 'wikidata_qid')
    op.drop_column('engines', 'source_id')
    op.drop_column('engines', 'superseded_by')
    op.drop_column('engines', 'scraped_at')
    op.drop_column('engines', 'confidence_score')
    op.drop_index(op.f('idx_generations_source_id'), table_name='generations')
    op.drop_index(op.f('idx_generations_superseded_by'), table_name='generations')
    op.drop_constraint(op.f('uq_generations_wikidata_qid'), 'generations', type_='unique')
    op.drop_constraint(op.f('fk_generations_source_id_sources'), 'generations', type_='foreignkey')
    op.drop_constraint(op.f('fk_generations_superseded_by_generations'), 'generations', type_='foreignkey')
    op.drop_column('generations', 'wikidata_qid')
    op.drop_column('generations', 'source_id')
    op.drop_column('generations', 'superseded_by')
    op.drop_column('generations', 'scraped_at')
    op.drop_column('generations', 'confidence_score')
    op.drop_index(op.f('idx_makes_source_id'), table_name='makes')
    op.drop_index(op.f('idx_makes_superseded_by'), table_name='makes')
    op.drop_constraint(op.f('uq_makes_wikidata_qid'), 'makes', type_='unique')
    op.drop_constraint(op.f('fk_makes_source_id_sources'), 'makes', type_='foreignkey')
    op.drop_constraint(op.f('fk_makes_superseded_by_makes'), 'makes', type_='foreignkey')
    op.drop_column('makes', 'wikidata_qid')
    op.drop_column('makes', 'source_id')
    op.drop_column('makes', 'superseded_by')
    op.drop_column('makes', 'scraped_at')
    op.drop_column('makes', 'confidence_score')
    op.drop_index(op.f('idx_model_years_source_id'), table_name='model_years')
    op.drop_index(op.f('idx_model_years_superseded_by'), table_name='model_years')
    op.drop_constraint(op.f('fk_model_years_source_id_sources'), 'model_years', type_='foreignkey')
    op.drop_constraint(op.f('fk_model_years_superseded_by_model_years'), 'model_years', type_='foreignkey')
    op.drop_column('model_years', 'confidence_score')
    op.drop_column('model_years', 'scraped_at')
    op.drop_column('model_years', 'superseded_by')
    op.drop_column('model_years', 'source_id')
    op.drop_index(op.f('idx_models_source_id'), table_name='models')
    op.drop_index(op.f('idx_models_superseded_by'), table_name='models')
    op.drop_constraint(op.f('uq_models_wikidata_qid'), 'models', type_='unique')
    op.drop_constraint(op.f('fk_models_superseded_by_models'), 'models', type_='foreignkey')
    op.drop_constraint(op.f('fk_models_source_id_sources'), 'models', type_='foreignkey')
    op.drop_column('models', 'wikidata_qid')
    op.drop_column('models', 'source_id')
    op.drop_column('models', 'superseded_by')
    op.drop_column('models', 'scraped_at')
    op.drop_column('models', 'confidence_score')
    op.drop_index(op.f('idx_transmissions_source_id'), table_name='transmissions')
    op.drop_index(op.f('idx_transmissions_superseded_by'), table_name='transmissions')
    op.drop_constraint(op.f('uq_transmissions_wikidata_qid'), 'transmissions', type_='unique')
    op.drop_constraint(op.f('fk_transmissions_source_id_sources'), 'transmissions', type_='foreignkey')
    op.drop_constraint(op.f('fk_transmissions_superseded_by_transmissions'), 'transmissions', type_='foreignkey')
    op.drop_column('transmissions', 'wikidata_qid')
    op.drop_column('transmissions', 'source_id')
    op.drop_column('transmissions', 'superseded_by')
    op.drop_column('transmissions', 'scraped_at')
    op.drop_column('transmissions', 'confidence_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transmissions', sa.Column('confidence_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('transmissions', sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('transmissions', sa.Column('superseded_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transmissions', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transmissions', sa.Column('wikidata_qid', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_transmissions_superseded_by_transmissions'), 'transmissions', 'transmissions', ['superseded_by'], ['id'])
    op.create_foreign_key(op.f('fk_transmissions_source_id_sources'), 'transmissions', 'sources', ['source_id'], ['id'])
    op.create_unique_constraint(op.f('uq_transmissions_wikidata_qid'), 'transmissions', ['wikidata_qid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_transmissions_superseded_by'), 'transmissions', ['superseded_by'], unique=False)
    op.create_index(op.f('idx_transmissions_source_id'), 'transmissions', ['source_id'], unique=False)
    op.add_column('models', sa.Column('confidence_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('models', sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('models', sa.Column('superseded_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('models', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('models', sa.Column('wikidata_qid', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_models_source_id_sources'), 'models', 'sources', ['source_id'], ['id'])
    op.create_foreign_key(op.f('fk_models_superseded_by_models'), 'models', 'models', ['superseded_by'], ['id'])
    op.create_unique_constraint(op.f('uq_models_wikidata_qid'), 'models', ['wikidata_qid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_models_superseded_by'), 'models', ['superseded_by'], unique=False)
    op.create_index(op.f('idx_models_source_id'), 'models', ['source_id'], unique=False)
    op.add_column('model_years', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('model_years', sa.Column('superseded_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('model_years', sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('model_years', sa.Column('confidence_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_model_years_superseded_by_model_years'), 'model_years', 'model_years', ['superseded_by'], ['id'])
    op.create_foreign_key(op.f('fk_model_years_source_id_sources'), 'model_years', 'sources', ['source_id'], ['id'])
    op.create_index(op.f('idx_model_years_superseded_by'), 'model_years', ['superseded_by'], unique=False)
    op.create_index(op.f('idx_model_years_source_id'), 'model_years', ['source_id'], unique=False)
    op.add_column('makes', sa.Column('confidence_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('makes', sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('makes', sa.Column('superseded_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('makes', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('makes', sa.Column('wikidata_qid', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_makes_superseded_by_makes'), 'makes', 'makes', ['superseded_by'], ['id'])
    op.create_foreign_key(op.f('fk_makes_source_id_sources'), 'makes', 'sources', ['source_id'], ['id'])
    op.create_unique_constraint(op.f('uq_makes_wikidata_qid'), 'makes', ['wikidata_qid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_makes_superseded_by'), 'makes', ['superseded_by'], unique=False)
    op.create_index(op.f('idx_makes_source_id'), 'makes', ['source_id'], unique=False)
    op.add_column('generations', sa.Column('confidence_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('generations', sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('generations', sa.Column('superseded_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('generations', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('generations', sa.Column('wikidata_qid', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_generations_superseded_by_generations'), 'generations', 'generations', ['superseded_by'], ['id'])
    op.create_foreign_key(op.f('fk_generations_source_id_sources'), 'generations', 'sources', ['source_id'], ['id'])
    op.create_unique_constraint(op.f('uq_generations_wikidata_qid'), 'generations', ['wikidata_qid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_generations_superseded_by'), 'generations', ['superseded_by'], unique=False)
    op.create_index(op.f('idx_generations_source_id'), 'generations', ['source_id'], unique=False)
    op.add_column('engines', sa.Column('confidence_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('engines', sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('engines', sa.Column('superseded_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('engines', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('engines', sa.Column('wikidata_qid', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_engines_source_id_sources'), 'engines', 'sources', ['source_id'], ['id'])
    op.create_foreign_key(op.f('fk_engines_superseded_by_engines'), 'engines', 'engines', ['superseded_by'], ['id'])
    op.create_unique_constraint(op.f('uq_engines_wikidata_qid'), 'engines', ['wikidata_qid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_engines_superseded_by'), 'engines', ['superseded_by'], unique=False)
    op.create_index(op.f('idx_engines_source_id'), 'engines', ['source_id'], unique=False)
    op.add_column('configurations', sa.Column('confidence_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('configurations', sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('configurations', sa.Column('superseded_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('configurations', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('configurations', sa.Column('wikidata_qid', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_configurations_source_id_sources'), 'configurations', 'sources', ['source_id'], ['id'])
    op.create_foreign_key(op.f('fk_configurations_superseded_by_configurations'), 'configurations', 'configurations', ['superseded_by'], ['id'])
    op.create_unique_constraint(op.f('uq_configurations_wikidata_qid'), 'configurations', ['wikidata_qid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_configurations_superseded_by'), 'configurations', ['superseded_by'], unique=False)
    op.create_index(op.f('idx_configurations_source_id'), 'configurations', ['source_id'], unique=False)
    op.drop_constraint(op.f('fk_configuration_transmissions_raw_record_id_raw_records'), 'configuration_transmissions', type_='foreignkey')
    op.drop_index(op.f('idx_configuration_transmissions_raw_record_id'), table_name='configuration_transmissions')
    op.drop_column('configuration_transmissions', 'raw_record_id')
    op.drop_constraint(op.f('fk_configuration_engines_raw_record_id_raw_records'), 'configuration_engines', type_='foreignkey')
    op.drop_index(op.f('idx_configuration_engines_raw_record_id'), table_name='configuration_engines')
    op.drop_column('configuration_engines', 'raw_record_id')
    op.drop_constraint(op.f('fk_configuration_attributes_raw_record_id_raw_records'), 'configuration_attributes', type_='foreignkey')
    op.drop_index(op.f('idx_configuration_attributes_raw_record_id'), table_name='configuration_attributes')
    op.drop_column('configuration_attributes', 'raw_record_id')
    op.drop_index('idx_field_provenance_transmission_id', table_name='field_provenance', postgresql_where=sa.text('transmission_id IS NOT NULL'))
    op.drop_index(op.f('idx_field_provenance_superseded_by'), table_name='field_provenance')
    op.drop_index('idx_field_provenance_source_id_field_name', table_name='field_provenance')
    op.drop_index(op.f('idx_field_provenance_source_id'), table_name='field_provenance')
    op.drop_index(op.f('idx_field_provenance_raw_record_id'), table_name='field_provenance')
    op.drop_index('idx_field_provenance_model_year_id', table_name='field_provenance', postgresql_where=sa.text('model_year_id IS NOT NULL'))
    op.drop_index('idx_field_provenance_model_id', table_name='field_provenance', postgresql_where=sa.text('model_id IS NOT NULL'))
    op.drop_index('idx_field_provenance_make_id', table_name='field_provenance', postgresql_where=sa.text('make_id IS NOT NULL'))
    op.drop_index('idx_field_provenance_generation_id', table_name='field_provenance', postgresql_where=sa.text('generation_id IS NOT NULL'))
    op.drop_index('idx_field_provenance_engine_id', table_name='field_provenance', postgresql_where=sa.text('engine_id IS NOT NULL'))
    op.drop_index('idx_field_provenance_configuration_id', table_name='field_provenance', postgresql_where=sa.text('configuration_id IS NOT NULL'))
    op.drop_table('field_provenance')
    op.drop_index(op.f('idx_external_ids_transmission_id'), table_name='external_ids')
    op.drop_index(op.f('idx_external_ids_source_id'), table_name='external_ids')
    op.drop_index(op.f('idx_external_ids_model_year_id'), table_name='external_ids')
    op.drop_index(op.f('idx_external_ids_model_id'), table_name='external_ids')
    op.drop_index(op.f('idx_external_ids_make_id'), table_name='external_ids')
    op.drop_index(op.f('idx_external_ids_generation_id'), table_name='external_ids')
    op.drop_index(op.f('idx_external_ids_engine_id'), table_name='external_ids')
    op.drop_index(op.f('idx_external_ids_configuration_id'), table_name='external_ids')
    op.drop_table('external_ids')
    op.drop_index('idx_raw_records_source_id_external_id', table_name='raw_records', schema='raw_scrape')
    op.drop_index(op.f('idx_raw_records_source_id'), table_name='raw_records', schema='raw_scrape')
    op.drop_index('idx_raw_records_content_hash', table_name='raw_records', schema='raw_scrape')
    op.drop_table('raw_records', schema='raw_scrape')
    # ### end Alembic commands ###
