"""vehicle derivations and derivation types (ADR 0005)

Auto-generated, then hand-reviewed. Verified present: both CHECK constraints
(confidence range, derived <> base), NULLS NOT DISTINCT on the natural key,
the partial index on derived_generation_id, and named FKs throughout.
Hand-added: the derivation_types seed rows (same idiom as company_roles in
5cbf6be81036) - `platform_shared` deliberately absent, see ADR 0005 SS5.

Revision ID: 05e766a04a5f
Revises: 5cbf6be81036
Create Date: 2026-07-27 13:12:13.902592

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e766a04a5f'
down_revision: str | Sequence[str] | None = '5cbf6be81036'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derivation_types',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_derivation_types')),
    sa.UniqueConstraint('code', name=op.f('uq_derivation_types_code'))
    )
    op.create_table('vehicle_derivations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_generation_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('derived_generation_id', sa.Integer(), nullable=True),
    sa.Column('derivation_type_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('raw_record_id', sa.BigInteger(), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name=op.f('ck_vehicle_derivations_confidence_score_range')),
    sa.CheckConstraint('derived_generation_id IS NULL OR derived_generation_id <> base_generation_id', name=op.f('ck_vehicle_derivations_derived_not_base')),
    sa.ForeignKeyConstraint(['base_generation_id'], ['generations.id'], name=op.f('fk_vehicle_derivations_base_generation_id_generations')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_vehicle_derivations_company_id_companies')),
    sa.ForeignKeyConstraint(['derivation_type_id'], ['derivation_types.id'], name=op.f('fk_vehicle_derivations_derivation_type_id_derivation_types')),
    sa.ForeignKeyConstraint(['derived_generation_id'], ['generations.id'], name=op.f('fk_vehicle_derivations_derived_generation_id_generations')),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_scrape.raw_records.id'], name=op.f('fk_vehicle_derivations_raw_record_id_raw_records')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_vehicle_derivations_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_derivations')),
    sa.UniqueConstraint('base_generation_id', 'company_id', 'derivation_type_id', 'derived_generation_id', name='uq_vehicle_derivations_natural_key', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('idx_vehicle_derivations_company_id'), 'vehicle_derivations', ['company_id'], unique=False)
    op.create_index(op.f('idx_vehicle_derivations_derivation_type_id'), 'vehicle_derivations', ['derivation_type_id'], unique=False)
    op.create_index('idx_vehicle_derivations_derived_generation_id', 'vehicle_derivations', ['derived_generation_id'], unique=False, postgresql_where=sa.text('derived_generation_id IS NOT NULL'))
    op.create_index(op.f('idx_vehicle_derivations_raw_record_id'), 'vehicle_derivations', ['raw_record_id'], unique=False)
    op.create_index(op.f('idx_vehicle_derivations_source_id'), 'vehicle_derivations', ['source_id'], unique=False)

    # ---- seed the derivation-type lookup (hand-added) ----------------------
    # `platform_shared` is deliberately not here: platform siblings have no
    # builder, no donor and no direction, so that relation belongs to a future
    # `platforms` entity (ADR 0005 SS5), not this table.
    op.execute(
        """
        INSERT INTO derivation_types (code, name, description) VALUES
          ('coachbuilt', 'Coachbuilt', 'Bodied by a coachbuilder; the car stays under the base make (Duesenberg Model J, body by Murphy)'),
          ('restomod',   'Restomod',   'Rebuilt from a donor vehicle into a distinct product (Singer DLS from the 964)'),
          ('tuned',      'Tuned',      'Mechanically transformed from a base vehicle (Alpina B3 from the BMW 3 Series)'),
          ('rebadged',   'Rebadged',   'Same vehicle sold under another company''s name (Toyota GR86 from the Subaru BRZ)')
        ON CONFLICT (code) DO NOTHING
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_vehicle_derivations_source_id'), table_name='vehicle_derivations')
    op.drop_index(op.f('idx_vehicle_derivations_raw_record_id'), table_name='vehicle_derivations')
    op.drop_index('idx_vehicle_derivations_derived_generation_id', table_name='vehicle_derivations', postgresql_where=sa.text('derived_generation_id IS NOT NULL'))
    op.drop_index(op.f('idx_vehicle_derivations_derivation_type_id'), table_name='vehicle_derivations')
    op.drop_index(op.f('idx_vehicle_derivations_company_id'), table_name='vehicle_derivations')
    op.drop_table('vehicle_derivations')
    op.drop_table('derivation_types')
    # ### end Alembic commands ###
