"""baseline phase 1 schema

Revision ID: 06582eecf0b2
Revises: 
Create Date: 2026-07-22 13:46:35.962273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06582eecf0b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('data_type', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('validation_regex', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_type IN ('text','integer','numeric','boolean')", name=op.f('ck_attribute_definitions_data_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribute_definitions')),
    sa.UniqueConstraint('key', name=op.f('uq_attribute_definitions_key'))
    )
    op.create_table('body_styles',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_styles')),
    sa.UniqueConstraint('code', name=op.f('uq_body_styles_code'))
    )
    op.create_table('drivetrains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drivetrains')),
    sa.UniqueConstraint('code', name=op.f('uq_drivetrains_code'))
    )
    op.create_table('fuel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fuel_types')),
    sa.UniqueConstraint('code', name=op.f('uq_fuel_types_code'))
    )
    op.create_table('market_regions',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_regions')),
    sa.UniqueConstraint('code', name=op.f('uq_market_regions_code'))
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('tier BETWEEN 1 AND 4', name=op.f('ck_sources_tier_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_table('transmission_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transmission_types')),
    sa.UniqueConstraint('code', name=op.f('uq_transmission_types_code'))
    )
    op.create_table('makes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('wikidata_qid', sa.Text(), nullable=True),
    sa.Column('country_code', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.SmallInteger(), nullable=True),
    sa.Column('defunct_year', sa.SmallInteger(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name=op.f('ck_makes_confidence_score_range')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_makes_source_id_sources')),
    sa.ForeignKeyConstraint(['superseded_by'], ['makes.id'], name=op.f('fk_makes_superseded_by_makes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_makes')),
    sa.UniqueConstraint('slug', name=op.f('uq_makes_slug')),
    sa.UniqueConstraint('wikidata_qid', name=op.f('uq_makes_wikidata_qid'))
    )
    op.create_index('idx_makes_name_trgm', 'makes', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('idx_makes_source_id'), 'makes', ['source_id'], unique=False)
    op.create_index(op.f('idx_makes_superseded_by'), 'makes', ['superseded_by'], unique=False)
    op.create_table('engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_make_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('family_code', sa.Text(), nullable=True),
    sa.Column('displacement_cc', sa.Integer(), nullable=True),
    sa.Column('cylinders', sa.SmallInteger(), nullable=True),
    sa.Column('configuration', sa.Text(), nullable=True),
    sa.Column('aspiration', sa.Text(), nullable=True),
    sa.Column('fuel_type_id', sa.Integer(), nullable=True),
    sa.Column('wikidata_qid', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name=op.f('ck_engines_confidence_score_range')),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], name=op.f('fk_engines_fuel_type_id_fuel_types')),
    sa.ForeignKeyConstraint(['manufacturer_make_id'], ['makes.id'], name=op.f('fk_engines_manufacturer_make_id_makes')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_engines_source_id_sources')),
    sa.ForeignKeyConstraint(['superseded_by'], ['engines.id'], name=op.f('fk_engines_superseded_by_engines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engines')),
    sa.UniqueConstraint('slug', name=op.f('uq_engines_slug')),
    sa.UniqueConstraint('wikidata_qid', name=op.f('uq_engines_wikidata_qid'))
    )
    op.create_index(op.f('idx_engines_fuel_type_id'), 'engines', ['fuel_type_id'], unique=False)
    op.create_index(op.f('idx_engines_manufacturer_make_id'), 'engines', ['manufacturer_make_id'], unique=False)
    op.create_index(op.f('idx_engines_source_id'), 'engines', ['source_id'], unique=False)
    op.create_index(op.f('idx_engines_superseded_by'), 'engines', ['superseded_by'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('wikidata_qid', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name=op.f('ck_models_confidence_score_range')),
    sa.ForeignKeyConstraint(['make_id'], ['makes.id'], name=op.f('fk_models_make_id_makes')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_models_source_id_sources')),
    sa.ForeignKeyConstraint(['superseded_by'], ['models.id'], name=op.f('fk_models_superseded_by_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models')),
    sa.UniqueConstraint('make_id', 'slug', name='uq_models_make_id_slug'),
    sa.UniqueConstraint('wikidata_qid', name=op.f('uq_models_wikidata_qid'))
    )
    op.create_index(op.f('idx_models_make_id'), 'models', ['make_id'], unique=False)
    op.create_index('idx_models_name_trgm', 'models', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('idx_models_source_id'), 'models', ['source_id'], unique=False)
    op.create_index(op.f('idx_models_superseded_by'), 'models', ['superseded_by'], unique=False)
    op.create_table('transmissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_make_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('transmission_type_id', sa.Integer(), nullable=True),
    sa.Column('gear_count', sa.SmallInteger(), nullable=True),
    sa.Column('wikidata_qid', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name=op.f('ck_transmissions_confidence_score_range')),
    sa.ForeignKeyConstraint(['manufacturer_make_id'], ['makes.id'], name=op.f('fk_transmissions_manufacturer_make_id_makes')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_transmissions_source_id_sources')),
    sa.ForeignKeyConstraint(['superseded_by'], ['transmissions.id'], name=op.f('fk_transmissions_superseded_by_transmissions')),
    sa.ForeignKeyConstraint(['transmission_type_id'], ['transmission_types.id'], name=op.f('fk_transmissions_transmission_type_id_transmission_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transmissions')),
    sa.UniqueConstraint('slug', name=op.f('uq_transmissions_slug')),
    sa.UniqueConstraint('wikidata_qid', name=op.f('uq_transmissions_wikidata_qid'))
    )
    op.create_index(op.f('idx_transmissions_manufacturer_make_id'), 'transmissions', ['manufacturer_make_id'], unique=False)
    op.create_index(op.f('idx_transmissions_source_id'), 'transmissions', ['source_id'], unique=False)
    op.create_index(op.f('idx_transmissions_superseded_by'), 'transmissions', ['superseded_by'], unique=False)
    op.create_index(op.f('idx_transmissions_transmission_type_id'), 'transmissions', ['transmission_type_id'], unique=False)
    op.create_table('generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('chassis_codes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('start_year', sa.SmallInteger(), nullable=True),
    sa.Column('end_year', sa.SmallInteger(), nullable=True),
    sa.Column('wikidata_qid', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name=op.f('ck_generations_confidence_score_range')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_generations_model_id_models')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_generations_source_id_sources')),
    sa.ForeignKeyConstraint(['superseded_by'], ['generations.id'], name=op.f('fk_generations_superseded_by_generations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generations')),
    sa.UniqueConstraint('model_id', 'slug', name='uq_generations_model_id_slug'),
    sa.UniqueConstraint('wikidata_qid', name=op.f('uq_generations_wikidata_qid'))
    )
    op.create_index(op.f('idx_generations_model_id'), 'generations', ['model_id'], unique=False)
    op.create_index(op.f('idx_generations_source_id'), 'generations', ['source_id'], unique=False)
    op.create_index(op.f('idx_generations_superseded_by'), 'generations', ['superseded_by'], unique=False)
    op.create_table('model_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name=op.f('ck_model_years_confidence_score_range')),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], name=op.f('fk_model_years_generation_id_generations')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_model_years_source_id_sources')),
    sa.ForeignKeyConstraint(['superseded_by'], ['model_years.id'], name=op.f('fk_model_years_superseded_by_model_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_years')),
    sa.UniqueConstraint('generation_id', 'year', name='uq_model_years_generation_id_year')
    )
    op.create_index(op.f('idx_model_years_generation_id'), 'model_years', ['generation_id'], unique=False)
    op.create_index(op.f('idx_model_years_source_id'), 'model_years', ['source_id'], unique=False)
    op.create_index(op.f('idx_model_years_superseded_by'), 'model_years', ['superseded_by'], unique=False)
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_year_id', sa.Integer(), nullable=False),
    sa.Column('market_region_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('wikidata_qid', sa.Text(), nullable=True),
    sa.Column('trim_name', sa.Text(), nullable=True),
    sa.Column('body_style_id', sa.Integer(), nullable=True),
    sa.Column('drivetrain_id', sa.Integer(), nullable=True),
    sa.Column('doors', sa.SmallInteger(), nullable=True),
    sa.Column('seating_capacity', sa.SmallInteger(), nullable=True),
    sa.Column('fuel_type_id', sa.Integer(), nullable=True),
    sa.Column('engine_displacement_cc', sa.Integer(), nullable=True),
    sa.Column('cylinders', sa.SmallInteger(), nullable=True),
    sa.Column('transmission_type_id', sa.Integer(), nullable=True),
    sa.Column('power_hp', sa.Integer(), nullable=True),
    sa.Column('torque_nm', sa.Integer(), nullable=True),
    sa.Column('mpg_city', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('mpg_highway', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('mpg_combined', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('mpge_combined', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('electric_range_km', sa.Integer(), nullable=True),
    sa.Column('curb_weight_kg', sa.Integer(), nullable=True),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('wheelbase_mm', sa.Integer(), nullable=True),
    sa.Column('msrp_launch_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('msrp_launch_currency', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name=op.f('ck_configurations_confidence_score_range')),
    sa.ForeignKeyConstraint(['body_style_id'], ['body_styles.id'], name=op.f('fk_configurations_body_style_id_body_styles')),
    sa.ForeignKeyConstraint(['drivetrain_id'], ['drivetrains.id'], name=op.f('fk_configurations_drivetrain_id_drivetrains')),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], name=op.f('fk_configurations_fuel_type_id_fuel_types')),
    sa.ForeignKeyConstraint(['market_region_id'], ['market_regions.id'], name=op.f('fk_configurations_market_region_id_market_regions')),
    sa.ForeignKeyConstraint(['model_year_id'], ['model_years.id'], name=op.f('fk_configurations_model_year_id_model_years')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_configurations_source_id_sources')),
    sa.ForeignKeyConstraint(['superseded_by'], ['configurations.id'], name=op.f('fk_configurations_superseded_by_configurations')),
    sa.ForeignKeyConstraint(['transmission_type_id'], ['transmission_types.id'], name=op.f('fk_configurations_transmission_type_id_transmission_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configurations')),
    sa.UniqueConstraint('model_year_id', 'slug', name='uq_configurations_model_year_id_slug'),
    sa.UniqueConstraint('wikidata_qid', name=op.f('uq_configurations_wikidata_qid'))
    )
    op.create_index(op.f('idx_configurations_body_style_id'), 'configurations', ['body_style_id'], unique=False)
    op.create_index(op.f('idx_configurations_drivetrain_id'), 'configurations', ['drivetrain_id'], unique=False)
    op.create_index(op.f('idx_configurations_fuel_type_id'), 'configurations', ['fuel_type_id'], unique=False)
    op.create_index(op.f('idx_configurations_market_region_id'), 'configurations', ['market_region_id'], unique=False)
    op.create_index(op.f('idx_configurations_model_year_id'), 'configurations', ['model_year_id'], unique=False)
    op.create_index(op.f('idx_configurations_source_id'), 'configurations', ['source_id'], unique=False)
    op.create_index(op.f('idx_configurations_superseded_by'), 'configurations', ['superseded_by'], unique=False)
    op.create_index(op.f('idx_configurations_transmission_type_id'), 'configurations', ['transmission_type_id'], unique=False)
    op.create_table('configuration_attributes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_integer', sa.BigInteger(), nullable=True),
    sa.Column('value_numeric', sa.Numeric(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('superseded_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name=op.f('ck_configuration_attributes_confidence_score_range')),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute_definitions.id'], name=op.f('fk_configuration_attributes_attribute_id_attribute_definitions')),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], name=op.f('fk_configuration_attributes_configuration_id_configurations')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_configuration_attributes_source_id_sources')),
    sa.ForeignKeyConstraint(['superseded_by'], ['configuration_attributes.id'], name=op.f('fk_configuration_attributes_superseded_by_configuration_attributes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuration_attributes'))
    )
    op.create_index(op.f('idx_configuration_attributes_attribute_id'), 'configuration_attributes', ['attribute_id'], unique=False)
    op.create_index(op.f('idx_configuration_attributes_configuration_id'), 'configuration_attributes', ['configuration_id'], unique=False)
    op.create_index(op.f('idx_configuration_attributes_source_id'), 'configuration_attributes', ['source_id'], unique=False)
    op.create_index(op.f('idx_configuration_attributes_superseded_by'), 'configuration_attributes', ['superseded_by'], unique=False)
    op.create_index('uq_configuration_attribute_live', 'configuration_attributes', ['configuration_id', 'attribute_id'], unique=True, postgresql_where=sa.text('superseded_by IS NULL'))
    op.create_table('configuration_engines',
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name=op.f('ck_configuration_engines_confidence_score_range')),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], name=op.f('fk_configuration_engines_configuration_id_configurations')),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], name=op.f('fk_configuration_engines_engine_id_engines')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_configuration_engines_source_id_sources')),
    sa.PrimaryKeyConstraint('configuration_id', 'engine_id', name=op.f('pk_configuration_engines'))
    )
    op.create_index(op.f('idx_configuration_engines_engine_id'), 'configuration_engines', ['engine_id'], unique=False)
    op.create_index(op.f('idx_configuration_engines_source_id'), 'configuration_engines', ['source_id'], unique=False)
    op.create_table('configuration_transmissions',
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('transmission_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.CheckConstraint('confidence_score BETWEEN 0 AND 1', name=op.f('ck_configuration_transmissions_confidence_score_range')),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], name=op.f('fk_configuration_transmissions_configuration_id_configurations')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_configuration_transmissions_source_id_sources')),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmissions.id'], name=op.f('fk_configuration_transmissions_transmission_id_transmissions')),
    sa.PrimaryKeyConstraint('configuration_id', 'transmission_id', name=op.f('pk_configuration_transmissions'))
    )
    op.create_index(op.f('idx_configuration_transmissions_source_id'), 'configuration_transmissions', ['source_id'], unique=False)
    op.create_index(op.f('idx_configuration_transmissions_transmission_id'), 'configuration_transmissions', ['transmission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_configuration_transmissions_transmission_id'), table_name='configuration_transmissions')
    op.drop_index(op.f('idx_configuration_transmissions_source_id'), table_name='configuration_transmissions')
    op.drop_table('configuration_transmissions')
    op.drop_index(op.f('idx_configuration_engines_source_id'), table_name='configuration_engines')
    op.drop_index(op.f('idx_configuration_engines_engine_id'), table_name='configuration_engines')
    op.drop_table('configuration_engines')
    op.drop_index('uq_configuration_attribute_live', table_name='configuration_attributes', postgresql_where=sa.text('superseded_by IS NULL'))
    op.drop_index(op.f('idx_configuration_attributes_superseded_by'), table_name='configuration_attributes')
    op.drop_index(op.f('idx_configuration_attributes_source_id'), table_name='configuration_attributes')
    op.drop_index(op.f('idx_configuration_attributes_configuration_id'), table_name='configuration_attributes')
    op.drop_index(op.f('idx_configuration_attributes_attribute_id'), table_name='configuration_attributes')
    op.drop_table('configuration_attributes')
    op.drop_index(op.f('idx_configurations_transmission_type_id'), table_name='configurations')
    op.drop_index(op.f('idx_configurations_superseded_by'), table_name='configurations')
    op.drop_index(op.f('idx_configurations_source_id'), table_name='configurations')
    op.drop_index(op.f('idx_configurations_model_year_id'), table_name='configurations')
    op.drop_index(op.f('idx_configurations_market_region_id'), table_name='configurations')
    op.drop_index(op.f('idx_configurations_fuel_type_id'), table_name='configurations')
    op.drop_index(op.f('idx_configurations_drivetrain_id'), table_name='configurations')
    op.drop_index(op.f('idx_configurations_body_style_id'), table_name='configurations')
    op.drop_table('configurations')
    op.drop_index(op.f('idx_model_years_superseded_by'), table_name='model_years')
    op.drop_index(op.f('idx_model_years_source_id'), table_name='model_years')
    op.drop_index(op.f('idx_model_years_generation_id'), table_name='model_years')
    op.drop_table('model_years')
    op.drop_index(op.f('idx_generations_superseded_by'), table_name='generations')
    op.drop_index(op.f('idx_generations_source_id'), table_name='generations')
    op.drop_index(op.f('idx_generations_model_id'), table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('idx_transmissions_transmission_type_id'), table_name='transmissions')
    op.drop_index(op.f('idx_transmissions_superseded_by'), table_name='transmissions')
    op.drop_index(op.f('idx_transmissions_source_id'), table_name='transmissions')
    op.drop_index(op.f('idx_transmissions_manufacturer_make_id'), table_name='transmissions')
    op.drop_table('transmissions')
    op.drop_index(op.f('idx_models_superseded_by'), table_name='models')
    op.drop_index(op.f('idx_models_source_id'), table_name='models')
    op.drop_index('idx_models_name_trgm', table_name='models', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('idx_models_make_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('idx_engines_superseded_by'), table_name='engines')
    op.drop_index(op.f('idx_engines_source_id'), table_name='engines')
    op.drop_index(op.f('idx_engines_manufacturer_make_id'), table_name='engines')
    op.drop_index(op.f('idx_engines_fuel_type_id'), table_name='engines')
    op.drop_table('engines')
    op.drop_index(op.f('idx_makes_superseded_by'), table_name='makes')
    op.drop_index(op.f('idx_makes_source_id'), table_name='makes')
    op.drop_index('idx_makes_name_trgm', table_name='makes', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('makes')
    op.drop_table('transmission_types')
    op.drop_table('sources')
    op.drop_table('market_regions')
    op.drop_table('fuel_types')
    op.drop_table('drivetrains')
    op.drop_table('body_styles')
    op.drop_table('attribute_definitions')
    # ### end Alembic commands ###
