"""reconciler state tables and companies.website (ADR 0007 s8)

Revision ID: 111a7cd329b8
Revises: d212a042caa7
Create Date: 2026-07-28 18:38:03.826836

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '111a7cd329b8'
down_revision: str | Sequence[str] | None = 'd212a042caa7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciled_records',
    sa.Column('raw_record_id', sa.BigInteger(), nullable=False),
    sa.Column('reconciled_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reconciler_version', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_scrape.raw_records.id'], name=op.f('fk_reconciled_records_raw_record_id_raw_records')),
    sa.PrimaryKeyConstraint('raw_record_id', name=op.f('pk_reconciled_records'))
    )
    op.create_table('reconciliation_flags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('generation_id', sa.Integer(), nullable=True),
    sa.Column('model_year_id', sa.Integer(), nullable=True),
    sa.Column('configuration_id', sa.Integer(), nullable=True),
    sa.Column('engine_id', sa.Integer(), nullable=True),
    sa.Column('transmission_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('raw_record_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("(kind = 'admission_review' AND num_nonnulls(company_id, model_id, generation_id, model_year_id, configuration_id, engine_id, transmission_id) = 0 AND raw_record_id IS NOT NULL) OR (kind <> 'admission_review' AND num_nonnulls(company_id, model_id, generation_id, model_year_id, configuration_id, engine_id, transmission_id) = 1)", name=op.f('ck_reconciliation_flags_flag_shape_matches_kind')),
    sa.CheckConstraint("kind IN ('field_conflict', 'multi_value', 'role_disagreement', 'admission_review', 'source_dropped')", name=op.f('ck_reconciliation_flags_kind_valid')),
    sa.CheckConstraint("status IN ('open', 'resolved', 'dismissed')", name=op.f('ck_reconciliation_flags_status_valid')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_reconciliation_flags_company_id_companies')),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], name=op.f('fk_reconciliation_flags_configuration_id_configurations')),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], name=op.f('fk_reconciliation_flags_engine_id_engines')),
    sa.ForeignKeyConstraint(['generation_id'], ['generations.id'], name=op.f('fk_reconciliation_flags_generation_id_generations')),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_reconciliation_flags_model_id_models')),
    sa.ForeignKeyConstraint(['model_year_id'], ['model_years.id'], name=op.f('fk_reconciliation_flags_model_year_id_model_years')),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_scrape.raw_records.id'], name=op.f('fk_reconciliation_flags_raw_record_id_raw_records')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_reconciliation_flags_source_id_sources')),
    sa.ForeignKeyConstraint(['transmission_id'], ['transmissions.id'], name=op.f('fk_reconciliation_flags_transmission_id_transmissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_flags'))
    )
    op.create_index('idx_reconciliation_flags_company_id', 'reconciliation_flags', ['company_id'], unique=False, postgresql_where=sa.text('company_id IS NOT NULL'))
    op.create_index('idx_reconciliation_flags_configuration_id', 'reconciliation_flags', ['configuration_id'], unique=False, postgresql_where=sa.text('configuration_id IS NOT NULL'))
    op.create_index('idx_reconciliation_flags_engine_id', 'reconciliation_flags', ['engine_id'], unique=False, postgresql_where=sa.text('engine_id IS NOT NULL'))
    op.create_index('idx_reconciliation_flags_generation_id', 'reconciliation_flags', ['generation_id'], unique=False, postgresql_where=sa.text('generation_id IS NOT NULL'))
    op.create_index('idx_reconciliation_flags_model_id', 'reconciliation_flags', ['model_id'], unique=False, postgresql_where=sa.text('model_id IS NOT NULL'))
    op.create_index('idx_reconciliation_flags_model_year_id', 'reconciliation_flags', ['model_year_id'], unique=False, postgresql_where=sa.text('model_year_id IS NOT NULL'))
    op.create_index('idx_reconciliation_flags_open', 'reconciliation_flags', ['kind', 'created_at'], unique=False, postgresql_where=sa.text("status = 'open'"))
    op.create_index(op.f('idx_reconciliation_flags_raw_record_id'), 'reconciliation_flags', ['raw_record_id'], unique=False)
    op.create_index(op.f('idx_reconciliation_flags_source_id'), 'reconciliation_flags', ['source_id'], unique=False)
    op.create_index('idx_reconciliation_flags_transmission_id', 'reconciliation_flags', ['transmission_id'], unique=False, postgresql_where=sa.text('transmission_id IS NOT NULL'))
    op.add_column('companies', sa.Column('website', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'website')
    op.drop_index('idx_reconciliation_flags_transmission_id', table_name='reconciliation_flags', postgresql_where=sa.text('transmission_id IS NOT NULL'))
    op.drop_index(op.f('idx_reconciliation_flags_source_id'), table_name='reconciliation_flags')
    op.drop_index(op.f('idx_reconciliation_flags_raw_record_id'), table_name='reconciliation_flags')
    op.drop_index('idx_reconciliation_flags_open', table_name='reconciliation_flags', postgresql_where=sa.text("status = 'open'"))
    op.drop_index('idx_reconciliation_flags_model_year_id', table_name='reconciliation_flags', postgresql_where=sa.text('model_year_id IS NOT NULL'))
    op.drop_index('idx_reconciliation_flags_model_id', table_name='reconciliation_flags', postgresql_where=sa.text('model_id IS NOT NULL'))
    op.drop_index('idx_reconciliation_flags_generation_id', table_name='reconciliation_flags', postgresql_where=sa.text('generation_id IS NOT NULL'))
    op.drop_index('idx_reconciliation_flags_engine_id', table_name='reconciliation_flags', postgresql_where=sa.text('engine_id IS NOT NULL'))
    op.drop_index('idx_reconciliation_flags_configuration_id', table_name='reconciliation_flags', postgresql_where=sa.text('configuration_id IS NOT NULL'))
    op.drop_index('idx_reconciliation_flags_company_id', table_name='reconciliation_flags', postgresql_where=sa.text('company_id IS NOT NULL'))
    op.drop_table('reconciliation_flags')
    op.drop_table('reconciled_records')
    # ### end Alembic commands ###
