"""unique raw_records (source_id, content_hash)

Revision ID: 24e7d0f5602c
Revises: a1c4e7b93f20
Create Date: 2026-07-24 14:01:11.016208

Makes re-scraping idempotent in the database rather than in application code,
ahead of the first real ingest. An unchanged payload hashes identically and is
rejected by this constraint, so a re-run cannot duplicate it - and `INSERT ...
ON CONFLICT DO NOTHING` becomes both the simplest and the race-safe way to land
a batch. A payload that genuinely changed hashes differently and still inserts,
preserving the change history that "raw data is never discarded" requires.

Autogenerated and hand-reviewed: schema qualification and the drop in
`downgrade()` were the two things to check, and both are correct.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24e7d0f5602c"
down_revision: str | Sequence[str] | None = "a1c4e7b93f20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_unique_constraint(
        "uq_raw_records_source_id_content_hash",
        "raw_records",
        ["source_id", "content_hash"],
        schema="raw_scrape",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "uq_raw_records_source_id_content_hash",
        "raw_records",
        schema="raw_scrape",
        type_="unique",
    )
