"""companies generalization, natural keys, media, search indexes

Revision ID: 5cbf6be81036
Revises: 24e7d0f5602c
Create Date: 2026-07-24 17:09:27.149907

Hand-written, not autogenerated. Autogenerate renders a rename as DROP + CREATE,
which would discard every row and every dependent foreign key; `ALTER TABLE ...
RENAME` preserves both. It also cannot see triggers, so the `updated_at` trigger
from `a1c4e7b93f20` is re-pointed here by hand.

Implements the pre-reconciler review (PROGRESS.md Review Findings) and ADR 0006:

  R1  makes -> companies, and every make_id -> company_id (ADR 0006)
  R2  field_provenance: at most one live assertion per (entity, field, source)
  R3  configurations: a real natural key, replacing the slug-based one
  R4  configurations.market_region_id NOT NULL
  R5  GIN index on generations.chassis_codes
  R7  trigram indexes on generations.name, configurations.trim_name, engines.name
  R8  currencies / countries / aspirations lookups replace free text
  R9  engines.configuration -> engines.cylinder_layout
  R11 media_assets + media_attachments
  R12 summary/description prose columns on every entity
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cbf6be81036"
down_revision: str | Sequence[str] | None = "24e7d0f5602c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Tables whose make-referencing column becomes company-referencing.
_MAKE_FK_TABLES = (
    ("models", "make_id", "company_id"),
    ("engines", "manufacturer_make_id", "manufacturer_company_id"),
    ("transmissions", "manufacturer_make_id", "manufacturer_company_id"),
    ("field_provenance", "make_id", "company_id"),
    ("external_ids", "make_id", "company_id"),
)

# The exclusive-arc columns, after the rename.
_ARC = (
    "company_id",
    "model_id",
    "generation_id",
    "model_year_id",
    "configuration_id",
    "engine_id",
    "transmission_id",
)

_ARC_TABLES = (
    "companies",
    "models",
    "generations",
    "model_years",
    "configurations",
    "engines",
    "transmissions",
)


def upgrade() -> None:
    """Upgrade schema."""

    # ---- R8: lookups for closed sets previously held as free text ----------
    for table in ("currencies", "countries", "aspirations"):
        op.create_table(
            table,
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("code", sa.Text(), nullable=False),
            sa.Column("name", sa.Text(), nullable=False),
            sa.PrimaryKeyConstraint("id", name=op.f(f"pk_{table}")),
            sa.UniqueConstraint("code", name=op.f(f"uq_{table}_code")),
        )

    op.create_table(
        "company_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_company_roles_code")),
    )

    # ---- R1: makes -> companies -------------------------------------------
    op.rename_table("makes", "companies")
    op.execute("ALTER INDEX uq_makes_slug RENAME TO uq_companies_slug")
    op.execute("ALTER INDEX pk_makes RENAME TO pk_companies")
    op.execute("ALTER INDEX idx_makes_name_trgm RENAME TO idx_companies_name_trgm")
    # The trigger survives the table rename but keeps its old name, which would
    # mislead the next person reading pg_trigger.
    op.execute(
        "ALTER TRIGGER trg_makes_set_updated_at ON companies "
        "RENAME TO trg_companies_set_updated_at"
    )

    for table, old_col, new_col in _MAKE_FK_TABLES:
        op.alter_column(table, old_col, new_column_name=new_col)

    # ---- R12 + R8: prose, and country as a FK ------------------------------
    op.add_column("companies", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column("companies", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("companies", sa.Column("country_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_companies_country_id_countries"),
        "companies",
        "countries",
        ["country_id"],
        ["id"],
    )
    op.create_index(op.f("idx_companies_country_id"), "companies", ["country_id"])
    op.drop_column("companies", "country_code")

    op.create_table(
        "company_role_assignments",
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("company_role_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("scraped_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("confidence_score", sa.Numeric(3, 2), nullable=True),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_role_assignments_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["company_role_id"],
            ["company_roles.id"],
            name=op.f("fk_company_role_assignments_company_role_id_company_roles"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_company_role_assignments_source_id_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_scrape.raw_records.id"],
            name=op.f("fk_company_role_assignments_raw_record_id_raw_records"),
        ),
        sa.PrimaryKeyConstraint(
            "company_id", "company_role_id", name=op.f("pk_company_role_assignments")
        ),
        sa.CheckConstraint("confidence_score BETWEEN 0 AND 1", name="confidence_score_range"),
    )
    op.create_index(
        op.f("idx_company_role_assignments_company_role_id"),
        "company_role_assignments",
        ["company_role_id"],
    )
    op.create_index(
        op.f("idx_company_role_assignments_source_id"), "company_role_assignments", ["source_id"]
    )
    op.create_index(
        op.f("idx_company_role_assignments_raw_record_id"),
        "company_role_assignments",
        ["raw_record_id"],
    )

    # ---- R12: summary on the remaining entities ----------------------------
    for table in ("models", "generations", "configurations", "engines", "transmissions"):
        op.add_column(table, sa.Column("summary", sa.Text(), nullable=True))

    # ---- R1: keys and indexes follow the column renames --------------------
    op.drop_constraint("uq_models_make_id_slug", "models", type_="unique")
    op.create_unique_constraint("uq_models_company_id_slug", "models", ["company_id", "slug"])
    op.execute("ALTER INDEX idx_models_make_id RENAME TO idx_models_company_id")
    op.execute(
        "ALTER INDEX idx_engines_manufacturer_make_id "
        "RENAME TO idx_engines_manufacturer_company_id"
    )
    op.execute(
        "ALTER INDEX idx_transmissions_manufacturer_make_id "
        "RENAME TO idx_transmissions_manufacturer_company_id"
    )
    op.execute("ALTER INDEX idx_field_provenance_make_id RENAME TO idx_field_provenance_company_id")
    op.execute("ALTER INDEX idx_external_ids_make_id RENAME TO idx_external_ids_company_id")

    # ---- R9: the name collision with the `configurations` entity -----------
    op.alter_column("engines", "configuration", new_column_name="cylinder_layout")
    op.add_column("engines", sa.Column("aspiration_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_engines_aspiration_id_aspirations"),
        "engines",
        "aspirations",
        ["aspiration_id"],
        ["id"],
    )
    op.create_index(op.f("idx_engines_aspiration_id"), "engines", ["aspiration_id"])
    op.drop_column("engines", "aspiration")

    # ---- R8: msrp currency -> FK -------------------------------------------
    op.add_column(
        "configurations", sa.Column("msrp_launch_currency_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_configurations_msrp_launch_currency_id_currencies"),
        "configurations",
        "currencies",
        ["msrp_launch_currency_id"],
        ["id"],
    )
    op.create_index(
        op.f("idx_configurations_msrp_launch_currency_id"),
        "configurations",
        ["msrp_launch_currency_id"],
    )
    op.drop_column("configurations", "msrp_launch_currency")

    # ---- R4: market is part of the atomic unit, so it cannot be NULL -------
    # GLOBAL and UNKNOWN are seeded first so existing rows have somewhere to go.
    op.execute(
        """
        INSERT INTO market_regions (code, name, description) VALUES
          ('GLOBAL',  'Global',  'Sold worldwide, or market not differentiated'),
          ('UNKNOWN', 'Unknown', 'Market not yet established for this configuration')
        ON CONFLICT (code) DO NOTHING
        """
    )
    op.execute(
        """
        UPDATE configurations SET market_region_id =
          (SELECT id FROM market_regions WHERE code = 'UNKNOWN')
        WHERE market_region_id IS NULL
        """
    )
    op.alter_column("configurations", "market_region_id", nullable=False)

    # ---- R3: the natural key ----------------------------------------------
    # NULLS NOT DISTINCT is load-bearing: by default NULLs never collide, so two
    # rows with an unknown trim or body style would both insert and the
    # constraint would do nothing for exactly the sparse records that need it.
    op.drop_constraint("uq_configurations_model_year_id_slug", "configurations", type_="unique")
    op.execute(
        """
        ALTER TABLE configurations
          ADD CONSTRAINT uq_configurations_natural_key
          UNIQUE NULLS NOT DISTINCT
          (model_year_id, trim_name, market_region_id, drivetrain_id, body_style_id)
        """
    )
    # Slug is now a display artifact, but /configurations/<slug> is a flat
    # route, so it must still resolve without knowing the model year.
    op.create_unique_constraint("uq_configurations_slug", "configurations", ["slug"])

    # ---- R2: at most one LIVE assertion per (entity, field, source) --------
    op.execute(
        f"""
        CREATE UNIQUE INDEX uq_field_provenance_live
          ON field_provenance ({", ".join(_ARC)}, field_name, source_id)
          NULLS NOT DISTINCT
          WHERE superseded_by IS NULL
        """
    )

    # ---- R5 + R7: search indexes -------------------------------------------
    op.execute("CREATE INDEX idx_generations_chassis_codes ON generations USING gin (chassis_codes)")
    op.execute("CREATE INDEX idx_generations_name_trgm ON generations USING gin (name gin_trgm_ops)")
    op.execute(
        "CREATE INDEX idx_configurations_trim_name_trgm "
        "ON configurations USING gin (trim_name gin_trgm_ops)"
    )
    op.execute("CREATE INDEX idx_engines_name_trgm ON engines USING gin (name gin_trgm_ops)")

    # ---- R11: media --------------------------------------------------------
    op.create_table(
        "media_assets",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("storage_url", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("license", sa.Text(), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("width_px", sa.Integer(), nullable=True),
        sa.Column("height_px", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.SmallInteger(), nullable=True),
        sa.Column("byte_size", sa.BigInteger(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("scraped_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("confidence_score", sa.Numeric(3, 2), nullable=True),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_media_assets_source_id_sources")
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_scrape.raw_records.id"],
            name=op.f("fk_media_assets_raw_record_id_raw_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_assets")),
        sa.CheckConstraint("kind IN ('image','document')", name="media_kind_valid"),
        sa.CheckConstraint(
            "storage_url IS NOT NULL OR source_url IS NOT NULL", name="media_has_location"
        ),
        sa.CheckConstraint("confidence_score BETWEEN 0 AND 1", name="confidence_score_range"),
    )
    op.create_index("idx_media_assets_content_hash", "media_assets", ["content_hash"])
    op.create_index("idx_media_assets_kind", "media_assets", ["kind"])
    op.create_index(op.f("idx_media_assets_source_id"), "media_assets", ["source_id"])
    op.create_index(op.f("idx_media_assets_raw_record_id"), "media_assets", ["raw_record_id"])

    op.create_table(
        "media_attachments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("media_asset_id", sa.BigInteger(), nullable=False),
        *(sa.Column(c, sa.Integer(), nullable=True) for c in _ARC),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["media_asset_id"],
            ["media_assets.id"],
            name=op.f("fk_media_attachments_media_asset_id_media_assets"),
            ondelete="CASCADE",
        ),
        *(
            sa.ForeignKeyConstraint([c], [f"{t}.id"], name=op.f(f"fk_media_attachments_{c}_{t}"))
            for c, t in zip(_ARC, _ARC_TABLES, strict=True)
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_attachments")),
        sa.CheckConstraint(f"num_nonnulls({', '.join(_ARC)}) = 1", name="exactly_one_entity"),
    )
    op.create_index(
        op.f("idx_media_attachments_media_asset_id"), "media_attachments", ["media_asset_id"]
    )
    op.execute(
        f"""
        ALTER TABLE media_attachments
          ADD CONSTRAINT uq_media_attachments_asset_entity_role
          UNIQUE NULLS NOT DISTINCT (media_asset_id, {", ".join(_ARC)}, role)
        """
    )
    for c in _ARC:
        op.execute(
            f"CREATE INDEX idx_media_attachments_{c} ON media_attachments ({c}) "
            f"WHERE {c} IS NOT NULL"
        )

    # ---- seed the role lookup ----------------------------------------------
    op.execute(
        """
        INSERT INTO company_roles (code, name, description) VALUES
          ('manufacturer',        'Manufacturer',        'Holds manufacturer responsibility for a finished vehicle (own WMI)'),
          ('coachbuilder',        'Coachbuilder',        'Bodies vehicles built by others'),
          ('restomodder',         'Restomodder',         'Rebuilds existing vehicles into a catalogued product'),
          ('tuner',               'Tuner',               'Modifies vehicles built by others'),
          ('designer',            'Designer',            'Designs vehicles built by others'),
          ('engine_manufacturer', 'Engine manufacturer', 'Builds engines, possibly for other companies')
        ON CONFLICT (code) DO NOTHING
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("media_attachments")
    op.drop_table("media_assets")

    for idx in (
        "idx_engines_name_trgm",
        "idx_configurations_trim_name_trgm",
        "idx_generations_name_trgm",
        "idx_generations_chassis_codes",
        "uq_field_provenance_live",
    ):
        op.execute(f"DROP INDEX IF EXISTS {idx}")

    op.drop_constraint("uq_configurations_slug", "configurations", type_="unique")
    op.drop_constraint("uq_configurations_natural_key", "configurations", type_="unique")
    op.create_unique_constraint(
        "uq_configurations_model_year_id_slug", "configurations", ["model_year_id", "slug"]
    )
    op.alter_column("configurations", "market_region_id", nullable=True)

    op.add_column("configurations", sa.Column("msrp_launch_currency", sa.Text(), nullable=True))
    op.drop_column("configurations", "msrp_launch_currency_id")

    op.add_column("engines", sa.Column("aspiration", sa.Text(), nullable=True))
    op.drop_column("engines", "aspiration_id")
    op.alter_column("engines", "cylinder_layout", new_column_name="configuration")

    op.execute("ALTER INDEX idx_external_ids_company_id RENAME TO idx_external_ids_make_id")
    op.execute("ALTER INDEX idx_field_provenance_company_id RENAME TO idx_field_provenance_make_id")
    op.execute(
        "ALTER INDEX idx_transmissions_manufacturer_company_id "
        "RENAME TO idx_transmissions_manufacturer_make_id"
    )
    op.execute(
        "ALTER INDEX idx_engines_manufacturer_company_id "
        "RENAME TO idx_engines_manufacturer_make_id"
    )
    op.execute("ALTER INDEX idx_models_company_id RENAME TO idx_models_make_id")
    op.drop_constraint("uq_models_company_id_slug", "models", type_="unique")

    for table in ("models", "generations", "configurations", "engines", "transmissions"):
        op.drop_column(table, "summary")

    op.drop_table("company_role_assignments")

    op.add_column("companies", sa.Column("country_code", sa.Text(), nullable=True))
    op.drop_column("companies", "country_id")
    op.drop_column("companies", "description")
    op.drop_column("companies", "summary")

    for table, old_col, new_col in _MAKE_FK_TABLES:
        op.alter_column(table, new_col, new_column_name=old_col)

    op.create_unique_constraint("uq_models_make_id_slug", "models", ["make_id", "slug"])

    op.execute(
        "ALTER TRIGGER trg_companies_set_updated_at ON companies "
        "RENAME TO trg_makes_set_updated_at"
    )
    op.execute("ALTER INDEX idx_companies_name_trgm RENAME TO idx_makes_name_trgm")
    op.execute("ALTER INDEX pk_companies RENAME TO pk_makes")
    op.execute("ALTER INDEX uq_companies_slug RENAME TO uq_makes_slug")
    op.rename_table("companies", "makes")

    op.drop_table("company_roles")
    for table in ("aspirations", "countries", "currencies"):
        op.drop_table(table)
