"""raw_records last_seen_at (F3)

Foundation review F3: the landing zone could not represent a source reverting
to a previous value. `last_seen_at` is bumped by the landing upsert on every
re-observation of an unchanged payload, so "the source's current record for an
entity" becomes max(last_seen_at) - which an A-B-A revert handles correctly by
re-touching the original row.

Hand-added: backfill to fetched_at. ADD COLUMN's default stamps existing rows
with migration time, but the truthful value for a row landed before this
column existed is the last time it was actually fetched.

Revision ID: 88079940a9e5
Revises: 05e766a04a5f
Create Date: 2026-07-28 11:13:50.083053

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88079940a9e5'
down_revision: str | Sequence[str] | None = '05e766a04a5f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_records', sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False), schema='raw_scrape')
    op.execute("UPDATE raw_scrape.raw_records SET last_seen_at = fetched_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_records', 'last_seen_at', schema='raw_scrape')
    # ### end Alembic commands ###
