"""model lines, memberships, and the match-decision log (ADR 0012)

Revision ID: a1756b039034
Revises: 76cb287dd71c
Create Date: 2026-07-30 17:19:53.610427

Autogenerated, then hand-reviewed. Three tables:

- `model_lines` - grouping rows for "3 Series"-shaped aggregations (ADR 0012
  §4): (company, slug, name), nothing in the FK spine points here, no
  external ids ever. Entity-shaped enough to carry TimestampMixin, so it
  gets the `updated_at` trigger autogenerate cannot see (the a1c4e7b93f20
  blind spot) - added by hand below.
- `model_line_members` - per-source membership assertions with supersession,
  the `company_role_assignments` shape: provenance columns per the charter's
  fact-table rule, live-unique per (line, model, source) NULLS NOT DISTINCT,
  deliberately never unique across sources.
- `match_decisions` - the match-decision log (2026-07-30 direction review):
  one upserted row per (source, pass, external_id) recording rung / method /
  outcome, so matcher precision is a query. No trigger: `decided_at` is
  rewritten by the upsert itself.

Downgrade drops all three - they hold only reconciler-derived state, which a
re-run rebuilds from raw.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1756b039034"
down_revision: str | Sequence[str] | None = "76cb287dd71c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match_decisions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("pass_name", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=True),
        sa.Column("rung", sa.Text(), nullable=True),
        sa.Column("method", sa.Text(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reconciler_version", sa.Text(), nullable=False),
        sa.Column(
            "decided_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_scrape.raw_records.id"],
            name=op.f("fk_match_decisions_raw_record_id_raw_records"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_match_decisions_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_decisions")),
        sa.UniqueConstraint(
            "source_id",
            "pass_name",
            "external_id",
            name="uq_match_decisions_source_id_pass_name_external_id",
        ),
    )
    op.create_index(
        "idx_match_decisions_pass_name_outcome",
        "match_decisions",
        ["pass_name", "outcome"],
        unique=False,
    )
    op.create_index(
        op.f("idx_match_decisions_raw_record_id"),
        "match_decisions",
        ["raw_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_match_decisions_source_id"), "match_decisions", ["source_id"], unique=False
    )
    op.create_table(
        "model_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_model_lines_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_lines")),
        sa.UniqueConstraint("company_id", "slug", name="uq_model_lines_company_id_slug"),
    )
    op.create_index(op.f("idx_model_lines_company_id"), "model_lines", ["company_id"], unique=False)
    op.create_table(
        "model_line_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_line_id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("superseded_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("raw_record_id", sa.BigInteger(), nullable=True),
        sa.Column("scraped_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("confidence_score", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.CheckConstraint(
            "confidence_score BETWEEN 0 AND 1",
            name=op.f("ck_model_line_members_confidence_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["model_id"], ["models.id"], name=op.f("fk_model_line_members_model_id_models")
        ),
        sa.ForeignKeyConstraint(
            ["model_line_id"],
            ["model_lines.id"],
            name=op.f("fk_model_line_members_model_line_id_model_lines"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_scrape.raw_records.id"],
            name=op.f("fk_model_line_members_raw_record_id_raw_records"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_model_line_members_source_id_sources")
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"], ["model_line_members.id"], name="fk_model_line_members_superseded_by"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_line_members")),
    )
    op.create_index(
        op.f("idx_model_line_members_model_id"), "model_line_members", ["model_id"], unique=False
    )
    op.create_index(
        op.f("idx_model_line_members_model_line_id"),
        "model_line_members",
        ["model_line_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_model_line_members_raw_record_id"),
        "model_line_members",
        ["raw_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_model_line_members_source_id"), "model_line_members", ["source_id"], unique=False
    )
    op.create_index(
        op.f("idx_model_line_members_superseded_by"),
        "model_line_members",
        ["superseded_by"],
        unique=False,
    )
    op.create_index(
        "uq_model_line_members_live",
        "model_line_members",
        ["model_line_id", "model_id", "source_id"],
        unique=True,
        postgresql_where=sa.text("superseded_by IS NULL"),
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###

    # Hand-written: the updated_at trigger for the new TimestampMixin table
    # (a1c4e7b93f20's function; triggers are autogenerate-invisible).
    op.execute(
        """
        CREATE TRIGGER trg_model_lines_set_updated_at
        BEFORE UPDATE ON model_lines
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_model_lines_set_updated_at ON model_lines;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_model_line_members_live",
        table_name="model_line_members",
        postgresql_where=sa.text("superseded_by IS NULL"),
        postgresql_nulls_not_distinct=True,
    )
    op.drop_index(op.f("idx_model_line_members_superseded_by"), table_name="model_line_members")
    op.drop_index(op.f("idx_model_line_members_source_id"), table_name="model_line_members")
    op.drop_index(op.f("idx_model_line_members_raw_record_id"), table_name="model_line_members")
    op.drop_index(op.f("idx_model_line_members_model_line_id"), table_name="model_line_members")
    op.drop_index(op.f("idx_model_line_members_model_id"), table_name="model_line_members")
    op.drop_table("model_line_members")
    op.drop_index(op.f("idx_model_lines_company_id"), table_name="model_lines")
    op.drop_table("model_lines")
    op.drop_index(op.f("idx_match_decisions_source_id"), table_name="match_decisions")
    op.drop_index(op.f("idx_match_decisions_raw_record_id"), table_name="match_decisions")
    op.drop_index("idx_match_decisions_pass_name_outcome", table_name="match_decisions")
    op.drop_table("match_decisions")
    # ### end Alembic commands ###
