"""updated_at trigger on entity tables

Revision ID: a1c4e7b93f20
Revises: 00531f09d08f
Create Date: 2026-07-24 00:00:00.000000

Hand-written, not autogenerated: Alembic cannot see triggers or functions, the
same blind spot that dropped the inline CHECK constraints in the baseline.

`TimestampMixin.updated_at` carries `onupdate=func.now()`, which SQLAlchemy
applies when *it* builds the UPDATE. Ingestion will not go through the ORM -
`INSERT ... ON CONFLICT DO UPDATE` and COPY are executed by Postgres directly,
so the ORM-side rule never fires and `updated_at` silently keeps its insert-time
value. The correct value is only knowable at write time, so a wrong one cannot
be backfilled later. Moving the rule into the database fixes it for every writer.

BEFORE UPDATE ... FOR EACH ROW, assigning one field on a tuple that is already
being rewritten: no I/O, no lookup. Fires on UPDATE only, never on INSERT.
"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1c4e7b93f20"
down_revision: str | Sequence[str] | None = "00531f09d08f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# The tables carrying TimestampMixin. Entity/identity tables only - fact-bearing
# rows use `scraped_at` instead, which records when the *source* was read.
TABLES = (
    "makes",
    "models",
    "generations",
    "model_years",
    "configurations",
    "engines",
    "transmissions",
)


def upgrade() -> None:
    """Upgrade schema."""
    # `IS DISTINCT FROM` so a no-op UPDATE (same values rewritten, which an
    # idempotent upsert does constantly) does not bump the timestamp. Without
    # it, a re-scrape that changed nothing would look like a modification and
    # the column would lose the meaning we want it for.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            IF NEW IS DISTINCT FROM OLD THEN
                NEW.updated_at = now();
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    for table in TABLES:
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_set_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at();
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    # Triggers first - the function cannot be dropped while they depend on it.
    for table in TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_set_updated_at ON {table};")

    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")
